[paths]
static_files = "static"
data_files = "data"

[csv_files]
uk = "data/amazon.uk.csv"
in = "data/amazon.in.csv"
us = "data/amazon.us.csv"
au = "data/amazon.au.csv"
fr = "data/amazon.fr.csv"
es = "data/amazon.es.csv"
it = "data/amazon.it.csv"
de = "data/amazon.de.csv"